

db = Database();

blank_datasets(db.repository(1), 5, "test_", ...
    @(i) struct( ...
        'type', 'test1', ...
        'number', i ...
    ), ...
    @(i) struct() )


blank_datasets(db.repository(2), 1, "aggregate", ...
    struct('type', 'aggregate_test1'), ...
    struct('test1', struct('repo', 1, 'dataset', {'test__00001','test__00002','test__00003','test__00004','test__00005'})) ...
    )

perform_task( db_bookmarks('test1'), t_duplicate_random_value() );
perform_task( db_bookmarks('aggtest1'), t_average_values() )

